LibraryTest/Controllers/JustUserBooksController.cs
using LibraryTest.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace LibraryTest.Controllers
{
    [Authorize(Roles = "JustUser")]
    public class JustUserBooksController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // POST: JustUserBooks/CancelReservation/5
        /// <summary>
        /// Отменяет бронь книги.
        /// </summary>
        /// <param name="id">Идентификатор книги, бронь которой необходимо отменить.</param>
        /// <returns>Возвращает Json результат: Success, Message, MessageType</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> CancelReservation(int? id)
        {
            if (id == null)
            {
                return Json(new { Message = "Ошибка, пустой идентификатор книги.", MessageType = "error" }, JsonRequestBehavior.DenyGet);
            }
            if (!(id is int)) //(id.GetType() != typeof(int))
            {
                return Json(new { Message = "Ошибка, недопустимый идентификатор книги.", MessageType = "error" }, JsonRequestBehavior.DenyGet);
            }
            try
            {
                BooksModel book = await db.Books.FindAsync(id);
                if (book == null)
                {
                    return Json(new { Message = "Ошибка, книга не найдена.", MessageType = "error" }, JsonRequestBehavior.DenyGet);
                }
                string UserId = User.Identity.GetUserId();
                if (UserId == null)
                {
                    return Json(
                        new {
                            Message = "Ошибка, вы не являетесь авторизованным пользователем.",
                            MessageType = "error"
                        }, 
                        JsonRequestBehavior.DenyGet
                    );
                }
                if (book.ApplicationUserId != UserId)
                {
                    return Json(new { Message = "Книга не была вами забронирована.", MessageType = "info" });
                }
                if (book.IssuingStatus == true)
                {
                    return Json(new { Message = "Бронь не была отменена, книга имеет статус выданной, сначала сдайте книгу в библиотеку.", MessageType = "info" });
                }
                book.ApplicationUserId = null;
                book.ApplicationUser = null;
                book.ReservationEnd = null;
                await db.SaveChangesAsync();
                await GeneralMethods.SendEmailRecentAttemptsReservationAsync(book, db);
                return Json(new { Message = "Бронь была отменена.", MessageType = "success" });
            }
            catch (Exception ex)
            {
                return Json(
                    new {
                        Message = "Исключение: " + ex.Message + " Внутреннее исключение: " + ex.InnerException.Message,
                        MessageType = "error"
                    },
                    JsonRequestBehavior.DenyGet
                );
            }
        }
        
        // POST: JustUserBooks/ReserveBook/5
        /// <summary>
        /// Бронирует книгу.
        /// </summary>
        /// <param name="id">Идентификатор книги, которой необходимо забронировать.</param>
        /// <returns>Возвращает Json результат: Success, Message, MessageType</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<JsonResult> ReserveBook(int? id)
        {            
            if (id == null)
            {
                return Json(new { Message = "Ошибка, пустой идентификатор книги.", MessageType = "error" }, JsonRequestBehavior.DenyGet);
            }
            if (!(id is int)) //(id.GetType() != typeof(int))
            {
                return Json(new { Message = "Ошибка, недопустимый идентификатор книги.", MessageType = "error" }, JsonRequestBehavior.DenyGet);
            }
            try
            {
                BooksModel book = await db.Books.FindAsync(id);
                if (book == null)
                {
                    return Json(new { Message = "Ошибка, книга не найдена.", MessageType = "error" }, JsonRequestBehavior.DenyGet);
                }
                string UserId = User.Identity.GetUserId();
                if (UserId == null)
                {
                    return Json(
                        new {
                            Message = "Не удалось забронировать книгу, так как только авторизованные пользователи имеют доступ к бронированию.",
                            MessageType = "info"
                        }, 
                        JsonRequestBehavior.DenyGet
                    );
                }
                if (book.ApplicationUser == null && book.ApplicationUserId == null)
                {
                    int MaxReserveCount = 3;
                    if (await db.ApplicationUsers.Where(a => a.Id == UserId && a.VerifiedByAdmin).CountAsync() == 0)
                    {
                        MaxReserveCount = 6;
                    }
                    if (await db.Books.Where(b => b.ApplicationUserId == UserId).CountAsync() < MaxReserveCount)
                    {
                        book.ApplicationUserId = UserId;
                        book.ReservationEnd = DateTime.Now.AddDays(3);
                        await db.SaveChangesAsync();
                        return Json(new { Message = "Книга забронирована за вами на три дня, после истечения срока бронь будет аннулирована!", MessageType = "success" }, JsonRequestBehavior.DenyGet);
                    }
                    else
                    {
                        return Json(
                            new {
                                Message = "Не удалось забронировать книгу, так как превышен лимит. Допускается бронирование только " + MaxReserveCount.ToString() + " книг единовременно.",
                                MessageType = "info"
                            },
                            JsonRequestBehavior.DenyGet
                        );
                    }
                }
                else if (book.ApplicationUserId != UserId)
                {
                    if (await db.RecentAttemptsReservationModels.FindAsync(UserId, book.Id) == null)
                    {
                        db.RecentAttemptsReservationModels.Add(new RecentAttemptsReservationModel { ApplicationUserId = UserId, BooksId = book.Id, AttemptDateTime = DateTime.Now });
                        await db.SaveChangesAsync();
                    } 
                    return Json(
                        new {
                            Message = "Книга уже является забронированной. Мы обязательно уведомим вас по email, когда она освободится.",
                            MessageType = "info"
                        },
                        JsonRequestBehavior.DenyGet
                    );
                }
                else
                {
                    return Json(new { Message = "Книга уже забронированна за вами.", MessageType = "info" }, JsonRequestBehavior.DenyGet);
                }
            }
            catch (Exception ex)
            {
                return Json(
                    new {
                        Message = "Исключение: " + ex.Message + " Внутреннее исключение: " + ex.InnerException.Message,
                        MessageType = "error"
                    },
                    JsonRequestBehavior.DenyGet
                );
            }
        }

        // GET: JustUserBooks
        public async Task<ActionResult> Index([Bind(Include = "FilterValue, FilterParameter, ReservationStatusParameter")] JustUsersBooksViewModel model)
        {
            IQueryable<BooksModel> books = db.Books.Include(b => b.ApplicationUser);
            if (!String.IsNullOrEmpty(model.FilterValue) && !String.IsNullOrWhiteSpace(model.FilterValue))
            {
                switch (model.FilterParameter)
                {
                    case JustUsersBooksViewModel.FilterParameters.Author:
                        books = books.Where(b => b.Author.Contains(model.FilterValue));
                        break;
                    case JustUsersBooksViewModel.FilterParameters.Genre:
                        books = books.Where(b => b.Ganre.Contains(model.FilterValue));
                        break;
                    case JustUsersBooksViewModel.FilterParameters.Publisher:
                        books = books.Where(b => b.Publisher.Contains(model.FilterValue));
                        break;
                    case JustUsersBooksViewModel.FilterParameters.Name:
                        books = books.Where(b => b.Name.Contains(model.FilterValue));
                        break;
                }              
            }
            string UserId = User.Identity.GetUserId();
            switch (model.ReservationStatusParameter)
            {
                case JustUsersBooksViewModel.ReservationStatusParameters.Available:
                    books = books.Where(b => b.ApplicationUser == null && b.ApplicationUserId == null);
                    break;
                case JustUsersBooksViewModel.ReservationStatusParameters.Reserved:
                    books = books.Where(b => b.ApplicationUser != null && b.ApplicationUserId != null);
                    break;
                case JustUsersBooksViewModel.ReservationStatusParameters.ReservedForMe:
                    books = books.Where(b => b.ApplicationUser != null && b.ApplicationUserId == UserId);
                    break;
                case JustUsersBooksViewModel.ReservationStatusParameters.IssuedToMe:

LibraryTest/Views/Shared/AfterUserCreatingMessage.cshtml
@{
    ViewBag.Title = "Библиотека";
}

<h2>На почтовый ящик пользователя послано сообщение с автоматически сгенерированным паролем.</h2>
<hr />
@Html.ActionLink("Вернуться к списку пользователей", "Index", "Admin")

LibraryTest/Views/Shared/EmailConfirmationMessage.cshtml
@{
    ViewBag.Title = "Библиотека";
}

<h2>На ваш почтовый ящик отправлено сообщение для подтверждения электронной почты.</h2>

LibraryTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    <link href="~/LT.ico" rel="shortcut icon" type="image/x-icon" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/sweetalert")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top" style="background-color:#1A237E; border-color:#1A237E">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
       
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Начальная страница", "Index", "Home")</li>
                    @if (User.IsInRole("Librarian"))
                    {
                        <li>@Html.ActionLink("Библиотекарю", "Index", "LibrarianBooks")</li>
                    }
                    @if (User.IsInRole("JustUser"))
                    {
                        <li>@Html.ActionLink("Список книг", "Index", "JustUserBooks")</li>
                    }
                    @if (User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Список пользователей", "Index", "Admin")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>